# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sewercalc
                                 A QGIS plugin
 Plugin para dimensionamento de redes coletoras de esgoto 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-07
        copyright            : (C) 2025 by Wanderilo  Lima
        email                : Wanderilo Lima
        git sha              : $Format:%H$
 ***************************************************************************/

"""

def classFactory(iface):  # pylint: disable=invalid-name
    from .Sewercalc import Sewercalc
    return Sewercalc(iface)
