# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sewercalc
                                 A QGIS plugin
 Plugin para dimensionamento de redes coletoras de esgoto 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-07
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Wanderilo  Lima
        email                : Wanderilo Lima
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from qgis.core import QgsProject, QgsVectorLayer, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsRaster
from qgis.PyQt.QtCore import QStandardPaths
from qgis.PyQt.QtCore import QVariant
from .Sewercalc_Estilo import aplicar_estilo
import numpy as np
import json
import os


def pontos_criticos(camada_rede, camada_mde, configuracoes, tabela_pv, tabela_rede):
    layer_mde = QgsProject.instance().mapLayer(camada_mde)
    layer_rede = QgsProject.instance().mapLayer(camada_rede)

    def encontrar_id(nome_pv):
        for id_pv, dados in tabela_pv.items():
            if dados['NOME'] == nome_pv:
                return id_pv
        return None

    def converter_null(tabela):
        if isinstance(tabela, dict):
            return {chave: converter_null(valor) for chave, valor in tabela.items()}
        elif isinstance(tabela, list):
            return [converter_null(item) for item in tabela]
        elif isinstance(tabela, QVariant):
            return tabela.toPyObject() if hasattr(tabela, "toPyObject") else str(tabela)
        elif tabela == "NULL":
            return None
        return tabela

    # obter as cotas do terreno ----------------------------------------------
    def obter_cotas_terreno(geom, passo):
        comprimento_geom = geom.length()
        interpol_x = np.arange(0, comprimento_geom + passo, passo)
        cotas_dict = {}

        for x in interpol_x:
            ponto = geom.interpolate(x)
            if not ponto or ponto.isEmpty():
                continue

            ident = layer_mde.dataProvider().identify(ponto.asPoint(), QgsRaster.IdentifyFormatValue)
            results = ident.results() if ident else None

            if results and 1 in results:
                cota = results[1]
            else:
                cota = None

            if cota is not None:
                cotas_dict[cota] = {
                    'xy': ponto.asPoint(),
                    'L': x
                }

        return cotas_dict


    pontos_criticos = {}
    for feicao_id, col in tabela_rede.items():
        pontos_criticos_trecho = {}
        pv_mont = col['PV_MONT']
        pv_jus = col['PV_JUS']
        nome = col['NOME']

        id_pv_mont = encontrar_id(pv_mont)
        id_pv_jus = encontrar_id(pv_jus)

        CFM = tabela_pv[id_pv_mont]['CTF']
        DN = col['DN']
        i = col['i']
        Rmin = float(configuracoes.get("Edit_R_min", 0))

        geom = None
        for trecho in layer_rede.getFeatures():
            if trecho.id() == feicao_id:
                geom = trecho.geometry()
                break

        if geom:
            tab_cotas = obter_cotas_terreno(geom, passo=1)

            if tab_cotas:
                for cota, info in tab_cotas.items():
                    CT_L = cota
                    L = info['L']
                    xy = info['xy']

                    CF_L = CFM - (L * i)
                    PFJ_L = CT_L - CF_L
                    RJ_L = PFJ_L - DN

                    if round(RJ_L, 2) < Rmin:
                        ponto_critico = {
                            'cota': round(cota, 3),
                            'trecho': nome,
                            'trecho_id': feicao_id,
                            'CF_L': round(CF_L, 3),
                            'PFJ_L': round(PFJ_L, 3),
                            'RJ_L': round(RJ_L, 3),
                            'L': round(L, 3),
                            'xy': xy
                        }
                        pontos_criticos_trecho[RJ_L] = ponto_critico

                if pontos_criticos_trecho:
                    menor_cota = min(pontos_criticos_trecho.keys())
                    info_menor_cota = pontos_criticos_trecho[menor_cota]
                    pontos_criticos[nome] = info_menor_cota

    #------------------Criando pontos-------------------
    crs_rede = layer_rede.crs().authid()
    pontos_criticos_layer = QgsVectorLayer(f"Point?crs={crs_rede}", "Pontos Críticos", "memory")
    provider = pontos_criticos_layer.dataProvider()
    provider.addAttributes([QgsField("TRECHO", QVariant.String),
                           QgsField("CT", QVariant.Double),
                           QgsField("CF", QVariant.Double),
                           QgsField("PF", QVariant.Double),
                           QgsField("REC", QVariant.Double),
                           QgsField("L", QVariant.Double)])
    pontos_criticos_layer.updateFields()

    for key, ponto in pontos_criticos.items():
        feat = QgsFeature()
        feat.setGeometry(QgsGeometry.fromPointXY(ponto['xy']))
        feat.setAttributes([ponto['trecho'],
                           ponto['cota'],
                           ponto['CF_L'],
                           ponto['PFJ_L'],
                           ponto['RJ_L'],
                           ponto['L']])
        provider.addFeature(feat)
    pontos_criticos_layer.updateExtents()
    QgsProject.instance().addMapLayer(pontos_criticos_layer)

    #salvando tabela------------------------
    pontos_criticos2 = {}
    pontos_criticos2 = {
        key: {k: v for k, v in value.items() if k != 'xy'}
        for key, value in pontos_criticos.items()
    }

    pontos_criticos_convertido = {}
    pontos_criticos_convertido = converter_null(pontos_criticos2)

    # Obter o caminho---------------------------------------------------
    config_dir = QStandardPaths.writableLocation(QStandardPaths.AppDataLocation)
    os.makedirs(config_dir, exist_ok=True) 
    arquivo_path = os.path.join(config_dir, "pontos_criticos.json")
        
    temp_path = arquivo_path + '.tmp'
       
    #Salvar os dados
    with open(temp_path, 'w', encoding='utf-8') as f:
        json.dump(pontos_criticos_convertido, f, indent=4, ensure_ascii=False)
        
    #Substituir o arquivo original
    if os.path.exists(temp_path):
        os.replace(temp_path, arquivo_path)
    
    aplicar_estilo(pontos_criticos_layer.id(), "Estilo Pnt_C.qml")
    