# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sewercalc
                                 A QGIS plugin
 Plugin para dimensionamento de redes coletoras de esgoto 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-07
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Wanderilo  Lima
        email                : Wanderilo Lima
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


from lxml import etree
import os
from datetime import datetime


def criar_landxml(tabela_pv, tabela_rede, epsg, pasta_salvar):
    epsg = str(epsg)
    dados_rede = {
    "nome": "Rede - Projeto",
    "tipo": "Sanitary",
    "descricao": "Rede de esgoto sanitário"
    }
    
    NSMAP = {None: "http://www.landxml.org/schema/LandXML-1.2"}
    root = etree.Element("LandXML", nsmap=NSMAP, version="1.2", date=datetime.now().strftime("%Y-%m-%d"))
    
     
    coordinate_system = etree.SubElement(root, "CoordinateSystem")
    etree.SubElement(coordinate_system, "PlanFeature", name="Sistema de Coordenadas", desc=f"EPSG:{epsg}")

    
    units = etree.SubElement(root, "Units")
    etree.SubElement(units, "Metric", linearUnit="meter", areaUnit="squareMeter", volumeUnit="cubicMeter")
    
    pipe_networks = etree.SubElement(root, "PipeNetworks")
    pipe_network = etree.SubElement(pipe_networks, "PipeNetwork", name=dados_rede["nome"], pipeNetType=dados_rede["tipo"], desc=dados_rede["descricao"])
    
    structs = etree.SubElement(pipe_network, "Structs")
    for id, col in tabela_pv.items():
        struct = etree.SubElement(structs, "Struct", 
                                  name=col["NOME"], 
                                  elevRim=str(col["CT"]), 
                                  elevSump=str(col["CTF"]), 
                                  desc="PV TIPO I"
                                  )
        etree.SubElement(struct, "Center").text = f"{col['y']} {col['x']}"
        etree.SubElement(struct, "CircStruct", diameter=str("0.6"), material="Reinforced Concrete")
    
    pipes = etree.SubElement(pipe_network, "Pipes") 
    for id, col in tabela_rede.items():
        pipe = etree.SubElement(pipes, "Pipe", 
                                name=col["NOME"], 
                                refStart=col["PV_MONT"], 
                                refEnd=col["PV_JUS"], 
                                length=str(col["L"]),
                                desc=(f"Tubo DN {round(col["DN"]*1000,0)}") 
                                )
        etree.SubElement(pipe, "CircPipe", diameter=str(col["DN"]*1000), material="PVC")   
    
    caminho_arquivo = os.path.join(pasta_salvar, "rede_esgoto.xml")
    with open(caminho_arquivo, "wb") as f:
        f.write(etree.tostring(root, pretty_print=True, encoding='utf-8', xml_declaration=True))
        
        
    return caminho_arquivo


#criar_landxml(dados_rede, tabela_pv, tabela_rede, "31984")